### ISSUE TITLE
Aruidno halts with ZMPT101B

### ISSUE THREAD

**Issue by qamarhafeez** [Abdurraziq/ZMPT101B-arduino#4]
Whenever there is a surge in electrical components like i turned on or off light of room or some other electric component, Arduino get halts when using ZMPT101B sensor. I am using this library to calculate voltage, please help.

**Comment by Abdurraziq** [comment]
Hai @qamarhafeez, I can only suggest these two solutions;  first keep the electrical equipment away from Arduino and secondly use a stable power supply that has protection against the surge effect.  I think the Arduino is hanging/halts due to a power surge that affects the arduino clock so that the program that is supposed to run becomes a hang.

_I hope this will solve your problem._

**Comment by qamarhafeez** [comment]
I have tested, the device halts only when AC power is added ZMPT101B sensor. Otherwise the device is working fine if AC power is disconnected from ZMPT101B. The device halts only when room switched is on or off.

**Comment by qamarhafeez** [comment]
Can you please suggest me where to add stable power supply and also suggest me the power supply that is stable, i think 5volt power supply added to arduino is stable.
